[tool:pytest]
DJANGO_SETTINGS_MODULE = posgrados_med.settings
python_files = tests.py test_*.py *_tests.py
testpaths = tests
addopts = -v --reuse-db --nomigrations --cov=catalogo --cov-report=html

markers =
    slow: mark tests as slow
    integration: mark tests as integration tests
    unit: mark tests as unit tests