# Generated by Django 5.2.1 on 2025-05-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id_admision', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=6)),
                ('fecha_inicio_inscripcion', models.DateField(blank=True, null=True)),
                ('fecha_cierre_inscripcion', models.DateField(blank=True, null=True)),
                ('fecha_examen_admision', models.DateField(blank=True, null=True)),
                ('fecha_publicacion_admitidos', models.DateField(blank=True, null=True)),
                ('paso_a_paso', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'admision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('codigo_snies', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=100)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_cupos', models.IntegerField(blank=True, null=True)),
                ('periocidad_admisiones', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('titulo_otorgado', models.CharField(blank=True, max_length=100, null=True)),
                ('total_creditos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programa_academico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id_universidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_universidad', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'universidad',
                'managed': False,
            },
        ),
    ]
